### PR TITLE
Maksym dev 01

### PR DESCRIPTION
**Pull request by NetGroup3**
i`m add Docker file and test connector to db.

### CODE REVIEW

**Comment by MaksimNemoshenkov** [comment]
ky

**Review by MaksimNemoshenkov — COMMENTED** [review]
11

**Review by MaksimNemoshenkov — COMMENTED** [review]
Good

**Review by MaksimNemoshenkov — APPROVED** [review]

**Review by MaksimNemoshenkov — APPROVED** [review]

**Review by MaksimNemoshenkov — APPROVED** [review]
1

**Review by MaksimNemoshenkov — APPROVED** [review]

**Review by MaksimNemoshenkov — APPROVED** [review]

**Review by MaksimNemoshenkov — CHANGES_REQUESTED** [review]
11

**Review by MaksimNemoshenkov — APPROVED** [review]

**Review by MaksimNemoshenkov — APPROVED** [review]

**Review by greg-source — APPROVED** [review]
Very nice

**Pull request closed without merging**
